/* Mock Data for the application */
export const musicLibrary = [
  {
    id: '1',
    title: 'Entrada Solene',
    composer: 'Mozart',
    duration: '3:45',
    degree: 'Aprendiz',
    ritual: 'Abertura',
    occasion: 'Solenidade',
    tone: 'Solene',
    isDownloaded: true,
    offlinePriority: true,
    isFavorite: true,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    cover:
      'https://img.usecurling.com/p/400/400?q=classical%20music&color=black',
  },
  {
    id: '2',
    title: 'Elevação Espiritual',
    composer: 'Bach',
    duration: '4:20',
    degree: 'Companheiro',
    ritual: 'Elevação',
    occasion: 'Regular',
    tone: 'Introspectivo',
    isDownloaded: true,
    offlinePriority: false,
    isFavorite: false,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    cover: 'https://img.usecurling.com/p/400/400?q=orchestra&color=black',
  },
  {
    id: '3',
    title: 'Meditação Profunda',
    composer: 'Beethoven',
    duration: '5:10',
    degree: 'Mestre',
    ritual: 'Exaltação',
    occasion: 'Magna',
    tone: 'Somente',
    isDownloaded: false,
    offlinePriority: false,
    isFavorite: true,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    cover: 'https://img.usecurling.com/p/400/400?q=piano&color=black',
  },
  {
    id: '4',
    title: 'Cadeia de União',
    composer: 'Sibelius',
    duration: '2:55',
    degree: 'Todos',
    ritual: 'Encerramento',
    occasion: 'Regular',
    tone: 'Fraternal',
    isDownloaded: true,
    offlinePriority: true,
    isFavorite: false,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    cover: 'https://img.usecurling.com/p/400/400?q=violin&color=black',
  },
  {
    id: '5',
    title: 'Harmonia Celeste',
    composer: 'Vivaldi',
    duration: '3:30',
    degree: 'Aprendiz',
    ritual: 'Abertura',
    occasion: 'Festiva',
    tone: 'Alegre',
    isDownloaded: false,
    offlinePriority: false,
    isFavorite: false,
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    cover: 'https://img.usecurling.com/p/400/400?q=harp&color=black',
  },
]

export const globalLibrary = [
  {
    id: 'g1',
    title: 'Hino Maçônico Nacional',
    composer: 'D. Pedro I',
    duration: '4:00',
    lodge: 'Loja GOB #1',
    degree: 'Todos',
    tags: ['Hino', 'Solenidade'],
  },
  {
    id: 'g2',
    title: 'Marcha de Entrada',
    composer: 'Wagner',
    duration: '3:15',
    lodge: 'Loja COMAB #55',
    degree: 'Mestre',
    tags: ['Entrada', 'Imponente'],
  },
  {
    id: 'g3',
    title: 'Momento de Reflexão',
    composer: 'Chopin',
    duration: '2:45',
    lodge: 'Grande Loja #33',
    degree: 'Aprendiz',
    tags: ['Silêncio', 'Reflexão'],
  },
  {
    id: 'g4',
    title: 'Fanfarra Real',
    composer: 'Desconhecido',
    duration: '1:30',
    lodge: 'Loja Unida #77',
    degree: 'Todos',
    tags: ['Entrada', 'Festiva'],
  },
  {
    id: 'g5',
    title: 'Adagio em Sol',
    composer: 'Albinoni',
    duration: '5:45',
    lodge: 'Loja Luz do Sul #12',
    degree: 'Companheiro',
    tags: ['Elevação', 'Triste'],
  },
]

export const playlists = [
  {
    id: '1',
    title: 'Sessão Magna de Iniciação',
    tracks: 12,
    duration: '45 min',
    cover:
      'https://img.usecurling.com/p/200/200?q=masonic%20ritual&color=black',
    items: ['1', '3', '5'],
  },
  {
    id: '2',
    title: 'Elevação Regular',
    tracks: 8,
    duration: '32 min',
    cover: 'https://img.usecurling.com/p/200/200?q=sheet%20music&color=black',
    items: ['2', '4'],
  },
  {
    id: '3',
    title: 'Banquete Ritualístico',
    tracks: 15,
    duration: '60 min',
    cover: 'https://img.usecurling.com/p/200/200?q=dinner&color=black',
    items: ['1', '2', '5'],
  },
]

export const lodgeMembers = [
  {
    id: '1',
    name: 'Ir. João Silva',
    email: 'joao@loja.com',
    role: 'Mestre de Harmonia',
    status: 'Ativo',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=1',
  },
  {
    id: '2',
    name: 'Ir. Carlos Souza',
    email: 'carlos@loja.com',
    role: 'Venerável Mestre',
    status: 'Ativo',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
  },
  {
    id: '3',
    name: 'Ir. Pedro Santos',
    email: 'pedro@loja.com',
    role: 'Secretário',
    status: 'Pendente',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=3',
  },
]

export const upcomingEvents = [
  {
    id: '1',
    title: 'Sessão Ordinária',
    date: '28 Jan, 20:00',
    type: 'Grau 1',
    playlistId: '2',
  },
  {
    id: '2',
    title: 'Iniciação',
    date: '04 Fev, 19:30',
    type: 'Magna',
    playlistId: '1',
  },
  {
    id: '3',
    title: 'Elevação',
    date: '11 Fev, 20:00',
    type: 'Grau 2',
    playlistId: null,
  },
]

export const chartData = [
  { name: 'Abertura', value: 400, fill: 'hsl(var(--chart-1))' },
  { name: 'Elevação', value: 300, fill: 'hsl(var(--chart-2))' },
  { name: 'Encerramento', value: 300, fill: 'hsl(var(--chart-3))' },
  { name: 'Outros', value: 200, fill: 'hsl(var(--chart-4))' },
]
